//! Build a job from the typed `ScriptHandle` generated by `#[chronon::script]`.
//!
//! Compared to stringly `Job::new("…", "script_name")`, the macro turns
//! `nightly_cleanup` into a handle factory and generates `NightlyCleanupParams`.
//! Use that handle to seed a default job, then set schedule fields and upsert.
//!
//! Run: `cargo run -p uf-chronon --example script_handle_job --features mem`

use std::sync::Arc;

use chrono::{Duration, Utc};
use chronon::prelude::*;
use chronon_backend_mem::InMemorySchedulerStore;

#[chronon::script(name = "nightly_cleanup")]
async fn nightly_cleanup(
    ctx: Box<dyn ScriptContext>,
    retention_days: u32,
) -> chronon::Result<()> {
    let _ = (ctx.label(), retention_days);
    Ok(())
}

#[tokio::main]
async fn main() -> chronon::Result<()> {
    let store = Arc::new(InMemorySchedulerStore::new());
    let chronon = ChrononBuilder::new()
        .scheduler_store(store)
        .context_factory(Arc::new(JsonScriptContextFactory))
        .embedded()
        .auto_registry()
        .build()?;

    let mut job = nightly_cleanup().job_with_params(
        "nightly-job",
        &NightlyCleanupParams {
            retention_days: 7,
        },
    )?;
    job.schedule_kind = ScheduleKind::RunOnce;
    job.next_run_at = Some(Utc::now() - Duration::seconds(60));
    chronon.coordinator_service().upsert_job(job).await?;

    chronon.scheduler.init_partitions().await;
    let tick = chronon.tick_once().await?;
    assert!(tick.enqueued >= 1);

    println!(
        "handle-built job; tick enqueued {} run(s)",
        tick.enqueued
    );
    Ok(())
}
